# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: proxy-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60
